### ISSUE TITLE
请问window下打包后为什么会报错在app.asar中无法找到node_modules/electron-asar-hot-updater/updater.exe，

### ISSUE THREAD

**Issue by TimZhou1011** [yansenlei/electron-asar-hot-updater#13]
用win包更新后，日志报错在app.asar中无法找到node_modules/electron-asar-hot-updater/updater.exe，程序弹窗报错error[6]，fail_apply那个错误，找了一个下午也不知道啥原因引起的，能不能帮我看一下，谢谢了大佬。

**Comment by yansenlei** [comment]
@TimZhou1011 

你好！

你可以用asar命令行工具解包你的.asar查看，在node_modules/electron-asar-hot-updater应该是没有的，因为在打包时不会拷贝.exe文件，如果你是用的`electron-builder`，目前我知道的方法，你可以这样配置让exe拷贝到app.asar中：
```js
files: [
  {
    "from": "node_modules/electron-asar-hot-updater",
    "to": "./node_modules/electron-asar-hot-updater",
    "filter": ["**/*"]
  }
]
```
文档：https://www.electron.build/configuration/contents.html

另外，刚刚提交一个版本，如果之前的`updater.exe`还存在但是写入新的`updater.exe`失败，不会报错会用旧的文件正常执行。你可以更新到`0.1.0`试试。

**Comment by yansenlei** [comment]
@TimZhou1011 
问题解决了吗？

**Comment by TimZhou1011** [comment]
> @TimZhou1011
> 问题解决了吗？

不好意思，一直忘记回复，我最终通过修改你的源代码，把路径地址修改成我自己需要的来解决这个问题了，感谢哈

**Comment by yansenlei** [comment]
好的，不客气
