### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by MesocCZ** [yansenlei/electron-asar-hot-updater#14]
Hello,
when I run my app with your updater I'm receiving following error.
```
Cannot read property 'includes' of undefined at Request._callback (C:\[notImportant]\electron-asar-hot-updater\index.js:228:48)
```
How can I fix it?

Thank you for your help.

**Comment by yansenlei** [comment]
@MesocCZ 

Thank you for your feedback!

I just pushed a new version, you can update it, try to fix it.

**Comment by MesocCZ** [comment]
It's working now, thank you!
