### ISSUE TITLE
'version_not_specified' what is causing this?

### ISSUE THREAD

**Issue by alvi1987** [yansenlei/electron-asar-hot-updater#15]
I have installed this package and configured it.
but when I try to run this I get the 'version_not_specified' error.

my package.json has following properties
```
 "name": "dess-ulo"
 "version": "1.0.0"
```

and the response i am getting from the API like following
```
{"source": "http://example.com/ulo_update/app_1_0_1.asar", "last": "1.0.1"}
```

What might be the problem?

**Comment by yansenlei** [comment]
Hi @alvi1987 

This error should come from here [#L128](https://github.com/yansenlei/electron-asar-hot-updater/blob/master/index.js#L128)

and have you tried the demo: https://github.com/yansenlei/asar-update-project

**Comment by alvi1987** [comment]
Hi @yansenlei thanks for the quick response. the packageinfo the check function is looking for its in wrong location. its not fetching the package.json from project root. Its getting it from 
```
/node_modules/electron-prebuilt/dist/resources/default_app.asar/
```

Can you point me to the right direction here?

**Comment by yansenlei** [comment]
Well, you can ignore him while you're developing: [asar-update-project/../index.js#L40](https://github.com/yansenlei/asar-update-project/blob/master/src/main/index.js#L40)

Thank you for your issue. I have added it to the [readme.md](https://github.com/yansenlei/electron-asar-hot-updater/commit/7ed2621353c06d22ae03b0062294c12cec371e7d)

**Comment by alvi1987** [comment]
@yansenlei thanks a lot
