### ISSUE TITLE
请问有没有遇到进度还在99%就卡住，实际更新已经完成的问题

### ISSUE THREAD

**Issue by TimZhou1011** [yansenlei/electron-asar-hot-updater#17]
我这边做了下载进度的显示，目前偶现这种问题：进度到99%的时候就卡住了，这时候去查看update-log，已经出现'End of update.'这样的日志了，实际上直接这时候关闭程序再开，也是已经更新好的版本了，不知道是怎么回事，我这边比较重要的代码如下，能不能帮我看看可能是什么情况引起的：
EAU.progress(function (state) {
        updateWindow.webContents.send('reply-progress', (state.percent * 100).toFixed(0))
        console.log(state)
        updateWindow.setProgressBar(state.percent)
    })
    EAU.download(function (error: any) {
        if (error) {
            dialog.showErrorBox('error', error)
            return false
        }
        if (process.platform === 'darwin') {
            app.relaunch()
            app.quit()
        } else {
            app.quit()
        }
    })

**Comment by yansenlei** [comment]
在什么系统环境下，各类版本号是多少？

**Comment by TimZhou1011** [comment]
> 在什么系统环境下，各类版本号是多少？

不好意思，这个问题是因为我进程其他部分的问题影响到了热更新的部分，这个可以关掉了哈，不好意思

**Comment by yansenlei** [comment]
ok
