### ISSUE TITLE
单纯的替换asar 能达到热更新的目的？

### ISSUE THREAD

**Issue by GlodenBoy** [yansenlei/electron-asar-hot-updater#22]
之前尝试过 直接替换新的asar重载页面回报错，应该有什么依赖。
作者解决了这个问题吗？

**Comment by yansenlei** [comment]
在mac还是win？win是不能在程序运行时替换的

**Comment by GlodenBoy** [comment]
> 在mac还是win？win是不能在程序运行时替换的

是在win下，win下有彻底热更的方案吗？

**Comment by yansenlei** [comment]
win下需要在程序关闭后替换asar，再次启动完成更新

**Comment by GlodenBoy** [comment]
> win下需要在程序关闭后替换asar，再次启动完成更新

是的，所以最后还不如 直接重新自动安装了。。

**Comment by yansenlei** [comment]
相比重新下载安装整个程序，asar会更小

**Comment by GlodenBoy** [comment]
> 相比重新下载安装整个程序，asar会更小

现在得asar文件挺大得，100多M，安装文件压缩成了70M，asar如果要小可需要压缩，没有测试打包成zip可以多小。

**Comment by yansenlei** [comment]
压缩成zip可以更小
```
-rw-r--r--   1 yansen.lei  2049091893  7809343  7  4 16:14 update.asar
-rw-rw-rw-   1 yansen.lei  2049091893  2050578 11  7 14:18 update.zip
```

**Comment by yansenlei** [comment]
可以在本地试试这个demo：https://github.com/yansenlei/asar-update-project
