### ISSUE TITLE
下载的时候，url路径是错误的，一直卡主，报err,没有走到回调函数里面，请问是什么原因呢

### ISSUE THREAD

**Issue by huoruji** [yansenlei/electron-asar-hot-updater#27]
下载的时候，url路径是错误的，一直卡主，报err,没有走到回调函数里面，请问是什么原因呢

**Comment by yansenlei** [comment]
提供下系统、版本等环境信息，可以去安装目录下的`updater.log`看看发生了什么

**Comment by huoruji** [comment]
electron 2.0.18 
node 10.15.1 32位
electron-asar-hot-updater 0.1.2
安装目录下没有产生updater.log日志
EAU.getVersion都报错 报EAU.getVersion is not a function
上上周还是可以更新的，这周直接报err

**Comment by yansenlei** [comment]
可以基于[示例工程](https://github.com/yansenlei/asar-update-project)复现问题吗？

**Comment by huoruji** [comment]
不好意思，后来发现是我们开发把源码改掉了，找到原因了，感谢回复
