### ISSUE TITLE
Downloading null，init的formatRes打印出来是正确的格式

### ISSUE THREAD

**Issue by TQGG** [yansenlei/electron-asar-hot-updater#30]
formatRes返回的是
{
  version: 'xxx',
  asar: 'xxx'
}
但是console里打印日志‘Downloading null’
最终走到了app.quit()但是asar没有更新
请问下有方法debug/找到问题所在吗？

**Comment by yansenlei** [comment]
formatRes的version有大于本地版本吗？https://github.com/yansenlei/electron-asar-hot-updater/blob/master/index.js#L211

**Comment by TQGG** [comment]
progress 和 download 没有写在check里导致，已跑通，我先close了，感谢。
