### ISSUE TITLE
请问怎样禁止应用更新完毕后重启呢

### ISSUE THREAD

**Issue by Atercia** [yansenlei/electron-asar-hot-updater#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yansenlei** [comment]
这是默认行为，暂不支持可选配置。

更新完默认重启体验应该更好吧？

**Comment by Atercia** [comment]
好的，谢谢，目前已解决，我尝试在EAU.download回调里面加了return false。

我在应用更新完后需要退出应用，用其它批处理命令重新启动app.exe以便给process传参，故整了个本地服务来调用.bat文件重启。
