### ISSUE TITLE
api/update.zip下载后未解压，直接替换了app.asar

### ISSUE THREAD

**Issue by Atercia** [yansenlei/electron-asar-hot-updater#41]
update.zip内容和要求一致，但是下载下来后并未被解压，而是直接变成了update.asar，并替换掉了现有的app.asar

**Comment by yansenlei** [comment]
> 并未被解压，而是直接变成了update.asar，并替换掉了现有的app.asar
这里被替换的app.asar，不是预期的update.asar吗？
```
── update.zip
   └── update.asar
```

**Comment by Atercia** [comment]
正常应该是update.zip被解压，得到里面的update.asar，然后改名变成app.asar，
但现在是update.zip直接被改后缀变成了update.asar，然后改名变成了app.asar。
也就是说，更新结束后app.asar文件变成了一个被改了后缀的压缩包，emmm

**Comment by Atercia** [comment]
已解决，后端接口未设置contentType字段为zip...
谢谢
