### ISSUE TITLE
This does not work for me

### ISSUE THREAD

**Issue by Pepnode** [yansenlei/electron-asar-hot-updater#7]
Dumping update log :

AppPath: xxxx
AppPathFolder: xxxxx
1.0.0
Update available: 1.0.1
Downloading http://www.abc.com/api/xyz/update_download/update.zip
Do something after request finishes
ZipFilePath: xxxx
Updater.update.file: F:\Users\xyz\Desktop\win-unpacked\resources\update.asar
Update Zip downloaded: F:\Users\xyz\Desktop\win-unpacked\resources\
Checking for F:\Users\xyz\Desktop\win-unpacked\resources\update.asar
Going to shell out to move: F:\xxx to: F:\xxx
Going to start the windows updater: F:\xxx\updater.exe F:\xxx\update.asar F:\xxx\resources\app.asar
"F:\xxx\updater.exe" "F:\xxx\resources\\update.asar" "F:\xxx\app.asar"

**Comment by Pepnode** [comment]
Update : the zip file gets downloaded but this happens :

AppPath: F:\Users\xyz\Desktop\win-unpacked\resources\app.asar/
AppPathFolder: F:\Users\xyz\Desktop\win-unpacked\resources\
1.0.0
Update available: 1.0.1
Downloading http://www.abc.com/api/xyz/update_download/update.zip
Do something after request finishes
ZipFilePath: F:\Users\xyz\Desktop\win-unpacked\resources\
unzip error: Invalid or unsupported zip format. No END header found

**Comment by yansenlei** [comment]
- What is the version of windows?

- How do you compress the zip？

- Is there any problem updating update.asar?

**Comment by Pepnode** [comment]
Thank you for responding @yansenlei 

Platform : Windows 7 (x64)

I have used WinRaR, 7-Zip and the node module 'adm-zip' to pack my asar file but none of them solved this issue. 

The asar file works just fine when I unpack the generated zip manually.

**Comment by yansenlei** [comment]
@Pepnode 

Ok, thank you for your feedback, I will reproduce this bug according to your environment.

Before that, can you try to use [adm-zip](https://www.npmjs.com/package/adm-zip) in your code? Because I used it to decompress.

**Comment by Pepnode** [comment]
@yansenlei I wrote a script using 'adm-zip' and successfully extracted the archive without any errors. But when I use the your code, it throws the exception 
"unzip error: Invalid or unsupported zip format. No END header found"

It is possible that the the archive is being extracted before it gets fully downloaded.

**Comment by Pepnode** [comment]
@yansenlei any luck?

**Comment by yansenlei** [comment]
@Pepnode 
I am pushed a update demo: https://github.com/yansenlei/asar-update-project

**Comment by Pepnode** [comment]
@yansenlei thank you! I got it to work.
