### ISSUE TITLE
Relaunch in windows

### ISSUE THREAD

**Issue by Manuel-777** [yansenlei/electron-asar-hot-updater#9]
Is it currently possible to relaunch the app under windows? I managed to get everything wrokinf, but oncet the `Updater.exe` replaces the original asar the app quits and the user would have to manually re-launch the app again.

Could this be added to  `Updater.exe`?

**Comment by yansenlei** [comment]
@Manuel-777 
yep, It will add the restart application feature in windows.

**Comment by yansenlei** [comment]
If you need it urgently, you can modify the [updater.cs](https://github.com/yansenlei/electron-asar-hot-updater/blob/master/updater.cs) file and submit PR
